---

- name: Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: Install epel-release
  package:
    name:
      - epel-release
    state: latest

- name: Install packages
  package:
    name:
      - nginx
      - audispd-plugins
    state: latest

- name: copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0755'
  notify: Restart nginx

- name: adding rule one to nginx
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    line: -w /etc/nginx/nginx.conf -p wa -k nginx_conf
    mode: '0640'
  
- name: adding rule two to nginx
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    line: -w /etc/nginx/default.d/ -p wa -k nginx_conf
    mode: '0640' 

- name: copy auditd config
  template:
    src: auditd.conf.j2
    dest: /etc/audit/auditd.conf
    mode: '0640'

- name: copy au-remote config
  template:
    src: au-remote.conf.j2
    dest: /etc/audisp/plugins.d/au-remote.conf
    mode: '0640'

- name: copy audisp-remote config
  template:
    src: audisp-remote.conf.j2
    dest: /etc/audisp/audisp-remote.conf
    mode: '0640'

- name: restart auditd
  command: service auditd restart
