---

- name: Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: Install packages
  package:
    name:
      - vim
      - nginx
      - auditd
      - audispd-plugins
    state: latest

- name: copy nginx config
  template: 
    src: nginx.conf.j2 
    dest: /etc/nginx/nginx.conf 
    mode: 0644
  notify: Restart nginx

- name: config auditd
  block:
    - name: adding rule one to nginx
      lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: -w /etc/nginx/nginx.conf -p wa -k nginx_conf
      
    - name: adding rule two to nginx
      lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: -w /etc/nginx/default.d/ -p wa -k nginx_conf
  
    - name: copy auditd config
      template: 
        src: auditd.conf.j2 
        dest: /etc/audit/auditd.conf
        mode: 0644
        
    - name: copy au-remote config
      template: 
        src: au-remote.conf.j2 
        dest: /etc/audisp/plugins.d/au-remote.conf
        mode: 0644
  
    - name: copy au-remote config
      template: 
        src: audisp-remote.conf.j2 
        dest: /etc/audisp/audisp-remote.conf
        mode: 0644
  notify: Restart auditd